FROM node:20-alpine

WORKDIR /app

# Copy node engine files
COPY node/package*.json ./
RUN npm install --omit=dev

COPY node/ .

EXPOSE 3100

ENV PORT=3100
ENV NODE_ENV=production

CMD ["node", "index.js"]
